### ISSUE TITLE
php warning

### ISSUE THREAD

**Issue by magnushasselquist** [Tazzios/cblistmodule#7]
Warning: foreach() argument must be of type array|object, null given in mod_cblistmodule/helper.php on line 92
(php version 8.0)
(latest version of cblistmodule)

**Comment by magnushasselquist** [comment]
Hi! Did you gave a chance to look at this issue? Not urgent, but probably quick fix if you have a quick look. Thanks! /Magnus

**Comment by Tazzios** [comment]
I lost a bit of motivation when trying to [rebuild the PDF editor button fo rJ4](https://github.com/Tazzios/pdfviewer/issues/29)

I looked at it but I have problems replicating. I do not know which one fieldtype you use; multicheckbox, multiselect, select or radio ? and what the users have selected.

**Comment by Tazzios** [comment]
@magnushasselquist  Now back in the correct issue instead of #6 

The problem does occur when the field value is changed (or a choice gets deleted). The user then still has the old value in the comprofiler table which cannot be found in the comprofiler_field_values table. I do not see another way then using the value to get the data. Value should not be changed because it is the Identifier. Label on the other hand can be changed without a problem.

So you could click on save for every user (or check the in comprofiler table the column for wrong values) then it should also go away.

An other solution is placing this if around the foreach but I`m not sure i want to do that. Instead I maybe should give a warning that a user has an invalid value.
```
if(!empty($labels)) {
    FOREACH
}
```

**Comment by Tazzios** [comment]
V3.0.4 is published. :)
